---
- name: Update windows system
  hosts: "{{ node_group | default('all') }}"
  serial: "{{ batch_size | default('33%') }}"
  gather_facts: false
  tags:
    - windows_update

  tasks:
    - name: Call windows update role to check if reboot is required before installing updates
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: is-reboot-required.yml

    # if you have a custom role to put the host in maintenance mode, you can call it here

    - name: Call windows update role to reboot host
      when: reboot_needed.result
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: reboot-host.yml

    - name: Call windows update role to search for updates
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: search-updates.yml
      tags:
        - search_updates

    - name: Call windows update role to download updates
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: download-updates.yml
      tags:
        - download_updates

    # if you have a custom role to take snapshot of the host before installing updates, you can call it here

    - name: Call windows update role to install updates
      when: updates_to_install
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: install-updates.yml
      tags:
        - install_updates

    - name: Call windows update role to check if reboot is required before installing updates
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: is-reboot-required.yml
      tags:
        - install_updates

    # if you have a custom role to put the host in maintenance mode, you can call it here

    - name: Call windows update role to reboot host
      when: reboot_needed.result
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: reboot-host.yml
