---
- name: Update windows system
  hosts: "{{ node_group | default('all') }}"
  serial: "{{ batch_size | default('33%') }}"
  gather_facts: false
  tags:
    - windows_update

  tasks:
    - name: Call windows update role to check if reboot is required before installing updates
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: is-reboot-required.yml

    # if reboot is required put the host in maintenance mode
    - name: Call custom role to put host in maintenance mode
      when: reboot_needed.result
      ansible.builtin.include_role:
        name: your-custom-role.zabbix_maintenance
      tags:
        - host_in_maintenance_mode

    - name: Call windows update role to reboot host
      when: reboot_needed.result
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: reboot-host.yml

    - name: Call windows update role to search for updates
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: search-updates.yml
      tags:
        - search_updates

    - name: Call windows update role to download updates
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: download-updates.yml
      tags:
        - download_updates

    # if there are updates to install, take a snapshot
    - name: Call custom role to take snapshot
      when: updates_to_install
      ansible.builtin.include_role:
        name: your-custom-role.vsphere_snapshot


    - name: Call windows update role to install updates
      when: updates_to_install
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: install-updates.yml
      tags:
        - install_updates

    - name: Call windows update role to check if reboot is required before installing updates
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: is-reboot-required.yml
      tags:
        - install_updates

    # if reboot is required put the host in maintenance mode
    - name: Call custom role to put host in maintenance mode
      when: reboot_needed.result
      ansible.builtin.include_role:
        name: your-custom-role.zabbix_maintenance
      tags:
        - host_in_maintenance_mode

    - name: Call windows update role to reboot host
      when: reboot_needed.result
      ansible.builtin.import_role:
        name: tvmalmeida.windows_update
        tasks_from: reboot-host.yml
